services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: saurabh_sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrongPassword123!
    networks:
      - saurabh_network

  redis:
    image: redis:alpine
    container_name: saurabh_redis
    networks:
      - saurabh_network

  backend:
    build:
      context: .
      dockerfile: HouseBroker.Api/Dockerfile
    container_name: saurabh_backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5107:8080"
    depends_on:
      - database
      - redis
    networks:
      - saurabh_network

networks:
  saurabh_network:
    driver: bridge